### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by TimvdLippe** [GoogleWebComponents/google-youtube-upload#11]
Upon clicking Sign in, I receive the following popup:

![image](https://cloud.githubusercontent.com/assets/5948271/14264021/2ee3217c-fabe-11e5-9467-2ed89c30f863.png)

**Comment by jeffposnick** [comment]
I think you stumbled upon the `http:` version of the page, instead of using `https:`. I've just whitelisted `http:`, to work as well.

**Comment by TimvdLippe** [comment]
I clicked on the demo on the linked component page. Can confirm it is fixed, thanks!
